name: .5-SAST-Check-Pull-Request-or-Branch

# This workflow will checkout the code, ZIP the Python file, and and scan with the Veracode Static Pipeline Scanner.
on:
  # Enables manual runs
  workflow_dispatch:
  # Runs "Every day at 4:05" (see https://crontab.guru)
  schedule:
  - cron: "5 4 * * *"

jobs:
  SAST-Check-Pull-Request-or-Branch:
    runs-on: [ubuntu-latest]
    steps:

# Checkout
      - uses: actions/checkout@v2
            
# ZIP up the Python files
      - name: Zip Application Files 
        uses: vimtor/action-zip@v1
        with:
          files: ./**
          dest: petstore-api-python.zip
  
# Download Veracode Static Pipeline Scanner     
      - name: Download Veracode Static Pipeline Scanner
        run: |
          curl https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip -o veracode.zip
          unzip -o veracode.zip
          
# In this configuration, the Pipeline scanner will check against the baseline file and see if there are any new flaws compared to the baseline.  If there is, it will break the build.  If not, the build will continue.  
      - name: Run Veracode Static Pipeline Scanner
        continue-on-error: true
        run: >
         java -jar pipeline-scan.jar --veracode_api_id "${{secrets.VERACODE_API_ID}}" --veracode_api_key "${{secrets.VERACODE_API_KEY}}"
         --file petstore-api-python.zip
         --summary_output true
         #--baseline_file vc-pipeline-scanner-baseline.json
         --project_name Petstore-API-GitHub
         
# Artifact the results for later use
      - name: Archive Results.json & Results.txt from Veracode Static Pipeline Scanner
        uses: actions/upload-artifact@v3.1.0
        with:
          # Artifact name
          name: Pipeline Scanner Results
          path: results.*         
