name: Everything in a single workflow

on:
  workflow_dispatch:
  schedule:
  - cron: "0 22 * * 1,3,5"

# Checkout, Artifact
jobs:
  Checkout-Artifact:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
            
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
        # Artifact name
          name: petstore-api-python.zip
          path: ./

      - name: ZIP up required files application files
        run: |
         zip petstore-api-python.zip api.py requirements.txt
         
      - name: List folder contents for visual
        run: |
         ls -la    

# Submit to Veracode for SAST and SCA Scan
      - name: Veracode Upload and Scan Action Step
        uses: veracode/veracode-uploadandscan-action@master
        id: upload_and_scan
        with:
          appname: 'PetstoreAPI-Python-GitHub'
          createprofile: false
          version: '${{ github.run_id }}-'
          criticality: Medium
          filepath: 'petstore-api-python.zip'
          vid: '${{ secrets.VERACODE_API_ID }}'
          vkey: '${{ secrets.VERACODE_API_KEY }}'
        continue-on-error: true  
        
# Dockerize and Publish

  Dockerize-Publish:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          push: true
          tags: veracodedemolabs/petstore_api_python_github:latest
          
# Deploy and run the Docker image for QA and DAST testing
  Deploy-Docker-Image-QA-Server:
    runs-on: [self-hosted]
    needs: Dockerize-Publish
    steps:         
#      - name: Terminate previous QA Docker image to run new version
#        run: |
#         docker stop petstore_api_python_github
#         docker rm petstore_api_python_github
        
       
# Pull new Docker image to QA web server
      - name: Pull new Docker image to QA web server
        run: |
         docker pull veracodedemolabs/petstore_api_python_github:latest
         
# Run Docker image on QA webserver for testing
      - name: Run Docker image
        run: |
         docker run -d --name petstore_api_python_github -p 5080:5000 veracodedemolabs/petstore_api_python_github:latest
         
